# Getting Started with Arrays - Python

##### Reference: https://www.udemy.com/course/python-arrays/learn/lecture/27293568#overview

In [1]:
# import packages

import numpy as np

In [2]:
# creating arrays 
# can be created 
np.array([1,2,3,4])

# or

np.array((1,2,3,4))

array([1, 2, 3, 4])

In [11]:
# can be created using the arange() method
# works just like your range() method
np.arange(5)

# or

np.arange(0,7,2)

array([0, 2, 4, 6])

In [7]:
# or with random integer function
# first and second argument is the start and stop numbers to generate random numbers between
# third is the shape of the array 5 for 1D, (2,3) 2 by 3 2D array
np.random.randint(1,26,5)

# or

np.random.randint(1,26,(2,3))

array([[19, 17, 23],
       [20, 22, 23]])

In [8]:
# to check the type of an array
arr = np.random.randint(1,26,5)
print (arr.dtype)

# Note
# If you store an array of ints and one element is float, the dtype of the array becomes float
# If you store an array of ints and one element is boolean, the dtype of the array becomes int
# If you store an array of ints and one element is float and another is boolean, the dtype of the array becomes float
# If you store an array of ints and one element is float, another is boolean, another is string, the dtype of the array becomes string

int64


In [26]:
# reshaping arrays
# first we create a 1D array

arr = np.random.randint(1,5,5)
arr = np.arange(1,13,1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
# check the shape and confirm it's 1D
arr.shape

(12,)

In [29]:
# re-shape the array
# to reshape to an evenly distributed array, you must have a total number of elements which is divisible by the array you are trying to reshape into

# re-shape to a 2x3 array
arr_2D = arr.reshape(2,6)
arr_2D

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [31]:
# re-shape to a 3x4
arr_3D = arr.reshape(3,4)
arr_3D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
# re-shaping to unknown dimensions
# only one unknown dimension can be provided
arr_unknown_dim = arr.reshape(-1,12)
arr_unknown_dim

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [35]:
arr_unknown_dim = arr.reshape(12,-1)
arr_unknown_dim

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [34]:
arr_unknown_dim = arr.reshape(4,-1)
arr_unknown_dim

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
a = ['tea', 'tea', 'act']
b = ['ate', 'toe', 'acts']
count = 0

for i,j in zip(a,b):
    if (set(i) != set(j)):
            count += 1
            print (count)
        #if set(i) == set(j):
        #print (set(i), set(j))

        #if sorted(list(i)) != sorted(list(j)):
         #   print (sorted(list(i)) , sorted(list(j)))
            #print ('yes')

1
2


In [48]:
def getMinimumDifference(a, b):
    outcome = []
    for i,j in zip(a,b):
        if set(i) == set(j):
            outcome.append(0) # store anagrams that do no need to be modified
        elif len(i) != len(j):
           outcome.append(-1) # store anagrams that contain different lenght of characters 
        else:
            count = 0
            if (set(i) != set(j)):
                count += 1
                outcome.append(count)  
    return outcome
        #elif len(i) != len(j):
        #   outcome.append(-1)

In [49]:
a = ['tea', 'tea', 'abb', 'act']
b = ['ate', 'toe', 'bbc', 'acts']
getMinimumDifference(a, b)

[0, 1, 1, -1]